### ISSUE TITLE
Write a developer's guide

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#10]
Write a developer's guide **using google docs**

**Comment by yun0000** [comment]
저 유저가이드 말고 이거 해도 될까요!!ㅠ

**Comment by binkoni** [comment]
네

**Comment by yun0000** [comment]
https://docs.google.com/document/d/13Xexr_mAYLJqQi-e_jITeP34amg-ASJzzYE3fQ2aNXE/edit?usp=sharing
