### ISSUE TITLE
 Implement playing sound effects and background music

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#12]
Implement playing sound effects and background music

**Comment by yun0000** [comment]
저 해보겠습니다!!

**Comment by yun0000** [comment]
저 왜 해지시키신건가요??ㅠ

**Comment by binkoni** [comment]
아 네 다른분들도 할게 있어야해서 일단 하나씩만 배정할게요
한다는 사람 더 없으면 다시 배정해드릴게요

**Comment by yun0000** [comment]
아아 넵 그러면 bgm이랑 효과음 찾아둔것까지만 풀 리퀘스트 하겠습니다

**Comment by cofls** [comment]
제가 해보겠습니다.

**Comment by binkoni** [comment]
그러면 채린님 이거 하고
윤주님 #18 하는걸로 할까요?

**Comment by cofls** [comment]
넵넵!!

**Comment by binkoni** [comment]
Done #50, without background music.
