### ISSUE TITLE
Implement ShootingSystem 

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#18]
Implement ShootingSystem using ShootingComp
Check every entity whether it satisfies ShootingComp.enabled == true and if so, add a bullet entity to the entities

**Comment by yun0000** [comment]
아아 넵 제가 해볼게요!
근데 아직 코드 구조가 머리속에 안들어와서 ㅠㅠㅠ
혹시 좀이따 질문좀 드려도 될까요..???..

**Comment by binkoni** [comment]
네네

**Comment by yun0000** [comment]
> Implement ShootingSystem using ShootingComp
> Check every entity whether it satisfies ShootingComp.enabled == true and if so, add a bullet entity to the entities

if so 이후에 add a ShootingComp to that entity's comps array
라고 이해하면 될까요???

**Comment by binkoni** [comment]
네 ShootingComp.enabled 가 true면 엔티티들에 Bullet 엔티티를 추가하시면 돼요.
그리고 [EntityManager가 구현되어서](https://github.com/stellar-fighter/stellar-fighter/commit/6a4d3de996dc0f2a592dac5ff6f1a74d0205244a) 이제 this.entities.push(entity) 가 아니라 this.entityMan.add(entity)로 추가하시면 됩니다.

**Comment by yun0000** [comment]
아아 네!! 제가 이상하게 이해하고 있었네요ㅠ 이제 제대로 이해했어요!!

**Comment by yun0000** [comment]
앗 근데 EntitiyMan 보다 EntityManager 이름이 더 볼때 편할거같은데 혹시 바꾸신 이유가 있으신가요..???

**Comment by binkoni** [comment]
manager를 man으로 줄이는 경우가 종종 있기도 하고.. this.entityMan 을 많이 타이핑 하다보니 타이핑 하기 귀찮아서 짧게 줄였어요 ㅋㅋ

**Comment by yun0000** [comment]
아항 넵 알겠습니다~!!😀😀

**Comment by binkoni** [comment]
모르고 merge했는데 문제점이 몇가지 있어서 고쳤습니다. 한번 [참고하세요](https://github.com/stellar-fighter/stellar-fighter/commit/6a8289641f65f91dbe27fd4192aec7ef00df6922)

**Comment by yun0000** [comment]
아아 넵 거의 새로 쓰셨네요 ㅠ ㅠ 죄송해요
참고해서 다음부터 주의하겠습니다
