### ISSUE TITLE
Design game screens(= pages, UIs)

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#2]
Design game screens using HTML and CSS or SCSS.

**Comment by rnjsdnfka** [comment]
저요

**Comment by mina0774** [comment]
저두용

**Comment by binkoni** [comment]
조민아님 organization 초대 보낸거 안 받으셔서 asignees에 할당이 안되네요

**Comment by mina0774** [comment]
아 네 죄송해요 ㅠㅠ 받았어용!!

**Comment by binkoni** [comment]
> 아 네 죄송해요 ㅠㅠ 받았어용!!

아직도 organization 멤버가 아니라고 나와요

**Comment by rnjsdnfka** [comment]
이거 저번에 아직 모르겠다고 답변해주신거 같은데 어떤식으로 할까요 ?

**Comment by binkoni** [comment]
음.. 일단은 기능은 구현 없이 SRS에 나온대로 HTML 페이지들만 몇 개 만들어 놓으면 될 것 같습니다.

**Comment by rnjsdnfka** [comment]
알겠습니다

**Comment by rnjsdnfka** [comment]
SRS에 있는 거는 호설씨가 만들었는데 스타트페이지만 있던걸로 기억하는데 다시 그냥 화면만 구성하나요 ??

**Comment by binkoni** [comment]
그냥 다시 화면만 구성한다는게 무슨 뜻인지 잘 이해가 안되는데 자세히 설명해주실래요?

**Comment by rnjsdnfka** [comment]
어떤게 필요하신지 잘 모르겠습니다 
SRS에 게임 시작 화면 게임중 화면 게임 오버 화면 세개있는데 호설씨가 화면 만든것처럼 그럼 화면만 필요로 하는건지 알려주시면 감사하겠습니다

**Comment by gonapps** [comment]
일반적인 게임 화면들 처럼 만들면 되죠 SRS 4쪽에 무슨 화면 필요한지 다 써있잖아요

**Comment by rnjsdnfka** [comment]
네

**Comment by rnjsdnfka** [comment]
감사합니다 지금 진행중입니다.

**Comment by rnjsdnfka** [comment]
참고해보겠습니다

**Comment by gonapps** [comment]
페이지 추가하려고 하는데 진행중인 것 맞나요
