### ISSUE TITLE
Implement a HP item

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#26]
Implement HP item that recover player's HP

**Comment by cofls** [comment]
이거 제가 해도 되나요...??!!!!
배경음악부터 얼른 하고 하겠습니당ㅎㅎ

**Comment by binkoni** [comment]
#29
전호설님이 구현하실 것 같습니다.

**Comment by wjsghtjf** [comment]
네네 entity generator할때  만들어두었어요 ㅠㅠㅠ 이미지만 저작권 문제없는거  찾아서 추가하면 될 것 같습니다
