### ISSUE TITLE
Implement PlayerSystem

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#31]
Separate [this code](https://github.com/stellar-fighter/stellar-fighter/blob/dev/src/states.js#L121) into PlayerSystem

**Comment by yun0000** [comment]
제가 해볼겠습니다

**Comment by yun0000** [comment]
커밋 확인해주실수 있으신가요?? 아직 임명?을 안받아서 풀리퀘스트를 안보냈습니다 ㅠ
전에 말씀해주신대로 최대한 하려했는데 플레이어는 엔티티 순회랑 조금 다른 것 같아서 적용을 많이 못했네요.. 틀린 부분 있으면 말씀주세요ㅠㅠ
그리고 시스템의 생성자에 compNames 는 제가 아직 이해를 못해서.. 어떤 걸 넣어야할지 모르겠어서 일단 비워두었습니다 ㅠㅠ

**Comment by yun0000** [comment]
아 그리고 괜찮다면 풀리퀘할때 총알 위치 수정해도 될까요??
지금 총알이 플레이어 좌상단에서 나오는데 중앙상단에서 나오면 더 좋을것같아서요!

**Comment by binkoni** [comment]
네
