### ISSUE TITLE
Add coolTime to CollComp, CollSystem

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#32]
Add coolTime to CollComp, CollSystem

**Comment by rnjsdnfka** [comment]
실력이 많이 부족한데 코드 추가해보고 싶어서 간단한 기능 있으시면 알려주시면 감사하겠습니다

**Comment by binkoni** [comment]
Done.
e7021443193cbf9565d19595d891eeca9d998875
