### ISSUE TITLE
Add comments to the code

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#40]
Add comments to the code

**Comment by rnjsdnfka** [comment]
Vector.js랑 다른 부분도 가능하다면 해보겠습니다

**Comment by rnjsdnfka** [comment]
다른 분들 코멘트 달고 계신거 적어주시면 좋을 거같아요 !

**Comment by binkoni** [comment]
함수 설명 & 함수 파라미터 주석은 오늘 중으로 제가 먼저 적어놓을테니 형식 참고해서 형식 지켜서 적어주세요

**Comment by binkoni** [comment]
그리고 다른 문서도 영어인만큼 주석도 영어로 달아주세요

**Comment by binkoni** [comment]
https://devhints.io/jsdoc
이 형식에 맞게 해주세요

**Comment by rnjsdnfka** [comment]
넵!

**Comment by rnjsdnfka** [comment]
오늘할게영

**Comment by rnjsdnfka** [comment]
vec.js 만 해서 보내볼께요

**Comment by rnjsdnfka** [comment]
/**
   * It is a function of obtaining a new vector by entering angle and magnitude.
   * @param {number} ang
   * @param {number} mag
   * @return {Vec} 
   * @example 
   */
  static fromAng(ang, mag) {
    return new Vec(mag * Math.cos(ang), mag * Math.sin(ang));
  }
이런식으로 해보고있는데 틀렸겠죠 ?...

**Comment by binkoni** [comment]
npm run build를 하신 다음에 dist/doc/index.html에서 문서 생성 결과를 확인해보면서 해보세요

**Comment by rnjsdnfka** [comment]
아하 확인했습니다 감사합니다

**Comment by rnjsdnfka** [comment]
/**
   * Returns 
   * @param {Vec} vec 
   */
  static fromVec(vec) {
    return new Vec(vec.x, vec.y);
  }
매개변수가 vec를 얻는 경우에  이런식으로 해도될까요 ?? 그리고 return 값 있는 함수는
Returns~~~~~ 했는데
set만 하는 함수는 Sets ~~~~이렇게해도되나요

**Comment by rnjsdnfka** [comment]
vec.js 해봤는데 생각보다 오래걸려서 이제 UI page도 해볼게요 수정할사항 많겠지만 말씀남겨주세요

**Comment by yun0000** [comment]
comps.js 이랑 scene_node.js 제가 작성하겠습니다1!

**Comment by binkoni** [comment]
[jsdoc](https://jsdoc.app)

**Comment by rnjsdnfka** [comment]
이 링크 좋은거 같네요

**Comment by yun0000** [comment]
systems.js 
states.js
entities.js
도 오늘 내로 작성하겠습니다

**Comment by rnjsdnfka** [comment]
assets.js 밤에 해봐도 될까요

**Comment by binkoni** [comment]
네

**Comment by binkoni** [comment]
기존 주석에서 문제를 발견했는데
생성자의 경우 Object 형태로 파라미터들을 받기 때문에 다음과 같이 바꿔야 합니다.
7a31621cc44ead552ead34474ec128f70c7e08db
https://jsdoc.app/tags-param.html#parameters-with-properties

**Comment by yun0000** [comment]
아아 넵 작성한 부분 수정하도록 하겠습니다 ㅠㅠ 죄송해요

**Comment by rnjsdnfka** [comment]
네 수정해보겠습니다 질문있는데 assets에 src같은경우에 {image} {audio} 괜찮을까요

**Comment by binkoni** [comment]
src는 string 입니다

**Comment by rnjsdnfka** [comment]
감사합니다

**Comment by yun0000** [comment]
camera.js
game.js
main.js
도 새벽 내로 작성하겠습니다

**Comment by yun0000** [comment]
혹시 더 작성할 js 파일이 있을까요??

**Comment by binkoni** [comment]
이제 더 없는 것 같네요
