### ISSUE TITLE
Write Final User Guide

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#59]
https://docs.google.com/document/d/1WlKR8SGXuuGhjPQAm8cFBX-rnfyIMGLDyenlhkEIz3I/edit?usp=sharing

**Comment by mina0774** [comment]
저 하겠습니다!

**Comment by rnjsdnfka** [comment]
같이할게요

**Comment by binkoni** [comment]
구글문서링크 올려주세요

**Comment by cofls** [comment]
저도 이거랑 테스트 레포트 부분만 할 수 있을 거 같아서 ㅠ 같이하겠습니다.

**Comment by binkoni** [comment]
박채린님은 다른 문서 해주세요
