### ISSUE TITLE
Write Project Review

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#62]

**Comment by rnjsdnfka** [comment]
교수님 답변 Project Review 는 한계점, 개선할 점 ( 쉽게 말하면 후기 ) 아쉬운 점

**Comment by mina0774** [comment]
https://docs.google.com/document/d/1Q9E3s6wFZp1hy8oDPEoDA6eUrBJ_488Pr25YJhUpWxk/edit?usp=sharing
