### ISSUE TITLE
Write an user guide

### ISSUE THREAD

**Issue by binkoni** [stellar-fighter/stellar-fighter#9]
Write an user guide **using google docs**

**Comment by yun0000** [comment]
제가 하겠습니다!

**Comment by rnjsdnfka** [comment]
같이 안댈까요?

**Comment by cofls** [comment]
저도요!!!!

**Comment by mina0774** [comment]
저도요!

**Comment by mina0774** [comment]
https://docs.google.com/document/d/1WlKR8SGXuuGhjPQAm8cFBX-rnfyIMGLDyenlhkEIz3I/edit?usp=sharing
